name: "Advent of Code Template"

description: "Create a Python template for an Advent of Code puzzle"

inputs:
  aoc_session_token:
    description: "Session token (cookie) for adventofcode.com"
    required: true
  year:
    description: "Calendar year of the event"
    required: false
  day:
    description: "Puzzle day"
    required: false
  source:
    description: "Source template directory"
    required: false
    default: "template/"
  output:
    description: "Output directory"
    required: false
    default: "output/"

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    AOC_SESSION: ${{ inputs.aoc_session_token }}
  args:
    - ${{ inputs.year }}
    - ${{ inputs.day }}
    - "--src"
    - ${{ inputs.source }}
    - "--output"
    - ${{ inputs.output }}
