name: "Advent of Code Template"

description: "Create a Python template for an Advent of Code puzzle"

inputs:
  aoc_session_token:
    description: "Session token (cookie) for adventofcode.com"
    required: true
  year:
    description: "Calendar year of the event"
    required: false
  day:
    description: "Puzzle day"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    AOC_SESSION_TOKEN: ${{ inputs.aoc_session_token }}
  args:
    - ${{ inputs.year }}
    - ${{ inputs.day }}
